import { db } from "./index"
import { buyers, buyerHistory } from "./schema"
import { nanoid } from "nanoid"

const seedBuyers = [
  {
    id: nanoid(),
    fullName: "Rajesh Kumar",
    email: "rajesh.kumar@email.com",
    phone: "9876543210",
    city: "Chandigarh",
    propertyType: "Apartment",
    bhk: "2",
    purpose: "Buy",
    budgetMin: 4500000,
    budgetMax: 5500000,
    timeline: "3-6m",
    source: "Website",
    status: "New",
    notes: "Looking for a property near IT Park",
    tags: JSON.stringify(["urgent", "family"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: nanoid(),
    fullName: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "9876543211",
    city: "Mohali",
    propertyType: "Villa",
    bhk: "3",
    purpose: "Buy",
    budgetMin: 7000000,
    budgetMax: 9000000,
    timeline: "0-3m",
    source: "Referral",
    status: "Contacted",
    notes: "Prefers Phase 7 location",
    tags: JSON.stringify(["premium", "garden"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: nanoid(),
    fullName: "Amit Patel",
    email: "amit.patel@email.com",
    phone: "9876543212",
    city: "Zirakpur",
    propertyType: "Office",
    purpose: "Rent",
    budgetMin: 50000,
    budgetMax: 80000,
    timeline: "Exploring",
    source: "Call",
    status: "Qualified",
    notes: "Looking for commercial space near highway",
    tags: JSON.stringify(["commercial", "highway"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: nanoid(),
    fullName: "Sunita Gupta",
    email: "sunita.gupta@email.com",
    phone: "9876543213",
    city: "Panchkula",
    propertyType: "Apartment",
    bhk: "1",
    purpose: "Rent",
    budgetMin: 15000,
    budgetMax: 25000,
    timeline: "0-3m",
    source: "Website",
    status: "New",
    notes: "First-time renter, needs furnished apartment",
    tags: JSON.stringify(["furnished", "first-time"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: nanoid(),
    fullName: "Vikram Singh",
    email: "vikram.singh@email.com",
    phone: "9876543214",
    city: "Chandigarh",
    propertyType: "Villa",
    bhk: "4",
    purpose: "Buy",
    budgetMin: 12000000,
    budgetMax: 15000000,
    timeline: ">6m",
    source: "Referral",
    status: "Visited",
    notes: "Looking for luxury villa with swimming pool",
    tags: JSON.stringify(["luxury", "pool", "spacious"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: nanoid(),
    fullName: "Meera Joshi",
    email: "meera.joshi@email.com",
    phone: "9876543215",
    city: "Mohali",
    propertyType: "Plot",
    purpose: "Buy",
    budgetMin: 3000000,
    budgetMax: 4000000,
    timeline: "3-6m",
    source: "Walk-in",
    status: "Negotiation",
    notes: "Wants to build custom home",
    tags: JSON.stringify(["plot", "construction"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: nanoid(),
    fullName: "Rohit Malhotra",
    email: "rohit.malhotra@email.com",
    phone: "9876543216",
    city: "Zirakpur",
    propertyType: "Apartment",
    bhk: "3",
    purpose: "Buy",
    budgetMin: 6000000,
    budgetMax: 7500000,
    timeline: "0-3m",
    source: "Website",
    status: "Qualified",
    notes: "Needs parking for 2 cars",
    tags: JSON.stringify(["parking", "urgent"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-21"),
  },
  {
    id: nanoid(),
    fullName: "Kavita Agarwal",
    email: "kavita.agarwal@email.com",
    phone: "9876543217",
    city: "Other",
    propertyType: "Retail",
    purpose: "Rent",
    budgetMin: 80000,
    budgetMax: 120000,
    timeline: "Exploring",
    source: "Call",
    status: "New",
    notes: "Looking for retail space for clothing store",
    tags: JSON.stringify(["retail", "clothing", "business"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: nanoid(),
    fullName: "Deepak Verma",
    email: "deepak.verma@email.com",
    phone: "9876543218",
    city: "Chandigarh",
    propertyType: "Apartment",
    bhk: "2",
    purpose: "Rent",
    budgetMin: 20000,
    budgetMax: 30000,
    timeline: "0-3m",
    source: "Referral",
    status: "Contacted",
    notes: "Young professional, prefers modern amenities",
    tags: JSON.stringify(["modern", "amenities", "professional"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-23"),
  },
  {
    id: nanoid(),
    fullName: "Anjali Kapoor",
    email: "anjali.kapoor@email.com",
    phone: "9876543219",
    city: "Panchkula",
    propertyType: "Villa",
    bhk: "3",
    purpose: "Buy",
    budgetMin: 8500000,
    budgetMax: 10000000,
    timeline: "3-6m",
    source: "Website",
    status: "Converted",
    notes: "Successfully purchased villa in Sector 5",
    tags: JSON.stringify(["converted", "satisfied"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-24"),
  },
  {
    id: nanoid(),
    fullName: "Manish Bhardwaj",
    email: "manish.bhardwaj@email.com",
    phone: "9876543220",
    city: "Mohali",
    propertyType: "Office",
    purpose: "Buy",
    budgetMin: 5000000,
    budgetMax: 7000000,
    timeline: ">6m",
    source: "Walk-in",
    status: "Dropped",
    notes: "Budget constraints, looking for smaller office",
    tags: JSON.stringify(["budget-issue", "small-office"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: nanoid(),
    fullName: "Sonia Reddy",
    email: "sonia.reddy@email.com",
    phone: "9876543221",
    city: "Zirakpur",
    propertyType: "Apartment",
    bhk: "1",
    purpose: "Buy",
    budgetMin: 2500000,
    budgetMax: 3200000,
    timeline: "0-3m",
    source: "Website",
    status: "Visited",
    notes: "First-time buyer, needs guidance",
    tags: JSON.stringify(["first-time", "guidance"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-26"),
  },
  {
    id: nanoid(),
    fullName: "Arjun Sethi",
    email: "arjun.sethi@email.com",
    phone: "9876543222",
    city: "Chandigarh",
    propertyType: "Plot",
    purpose: "Buy",
    budgetMin: 4500000,
    budgetMax: 6000000,
    timeline: "Exploring",
    source: "Referral",
    status: "New",
    notes: "Interested in corner plot for better access",
    tags: JSON.stringify(["corner-plot", "access"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-27"),
  },
  {
    id: nanoid(),
    fullName: "Pooja Bansal",
    email: "pooja.bansal@email.com",
    phone: "9876543223",
    city: "Panchkula",
    propertyType: "Apartment",
    bhk: "Studio",
    purpose: "Rent",
    budgetMin: 12000,
    budgetMax: 18000,
    timeline: "0-3m",
    source: "Call",
    status: "Qualified",
    notes: "Student accommodation near university",
    tags: JSON.stringify(["student", "university", "budget"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-28"),
  },
  {
    id: nanoid(),
    fullName: "Ravi Chopra",
    email: "ravi.chopra@email.com",
    phone: "9876543224",
    city: "Mohali",
    propertyType: "Villa",
    bhk: "4",
    purpose: "Rent",
    budgetMin: 60000,
    budgetMax: 80000,
    timeline: "3-6m",
    source: "Website",
    status: "Negotiation",
    notes: "Corporate executive, needs furnished villa",
    tags: JSON.stringify(["corporate", "furnished", "executive"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-29"),
  },
  {
    id: nanoid(),
    fullName: "Neha Sood",
    email: "neha.sood@email.com",
    phone: "9876543225",
    city: "Other",
    propertyType: "Retail",
    purpose: "Buy",
    budgetMin: 8000000,
    budgetMax: 12000000,
    timeline: ">6m",
    source: "Walk-in",
    status: "Contacted",
    notes: "Planning to open restaurant chain",
    tags: JSON.stringify(["restaurant", "chain", "business"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: nanoid(),
    fullName: "Gaurav Mittal",
    email: "gaurav.mittal@email.com",
    phone: "9876543226",
    city: "Zirakpur",
    propertyType: "Apartment",
    bhk: "2",
    purpose: "Buy",
    budgetMin: 3800000,
    budgetMax: 4500000,
    timeline: "0-3m",
    source: "Referral",
    status: "Visited",
    notes: "Newlywed couple, first home purchase",
    tags: JSON.stringify(["newlywed", "first-home", "couple"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-01-31"),
  },
  {
    id: nanoid(),
    fullName: "Simran Kaur",
    email: "simran.kaur@email.com",
    phone: "9876543227",
    city: "Chandigarh",
    propertyType: "Office",
    purpose: "Rent",
    budgetMin: 40000,
    budgetMax: 60000,
    timeline: "0-3m",
    source: "Website",
    status: "New",
    notes: "IT startup, needs modern office space",
    tags: JSON.stringify(["startup", "IT", "modern"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: nanoid(),
    fullName: "Harpreet Gill",
    email: "harpreet.gill@email.com",
    phone: "9876543228",
    city: "Panchkula",
    propertyType: "Villa",
    bhk: "3",
    purpose: "Buy",
    budgetMin: 9000000,
    budgetMax: 11000000,
    timeline: "3-6m",
    source: "Call",
    status: "Qualified",
    notes: "Retired couple, wants peaceful location",
    tags: JSON.stringify(["retired", "peaceful", "couple"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-02-02"),
  },
  {
    id: nanoid(),
    fullName: "Tarun Aggarwal",
    email: "tarun.aggarwal@email.com",
    phone: "9876543229",
    city: "Mohali",
    propertyType: "Plot",
    purpose: "Buy",
    budgetMin: 2800000,
    budgetMax: 3500000,
    timeline: "Exploring",
    source: "Referral",
    status: "Contacted",
    notes: "Investment purpose, good location preferred",
    tags: JSON.stringify(["investment", "location", "future"]),
    ownerId: "agent-1",
    updatedAt: new Date("2024-02-03"),
  },
  {
    id: nanoid(),
    fullName: "Divya Malhotra",
    email: "divya.malhotra@email.com",
    phone: "9876543230",
    city: "Other",
    propertyType: "Apartment",
    bhk: "3",
    purpose: "Rent",
    budgetMin: 35000,
    budgetMax: 45000,
    timeline: "0-3m",
    source: "Website",
    status: "Converted",
    notes: "Successfully rented 3BHK in Sector 22",
    tags: JSON.stringify(["converted", "family", "satisfied"]),
    ownerId: "admin-1",
    updatedAt: new Date("2024-02-04"),
  },
]

export async function seedDatabase() {
  try {
    console.log("Seeding database...")
    
    // Clear existing data
    await db.delete(buyerHistory)
    await db.delete(buyers)
    
    // Insert seed data
    await db.insert(buyers).values(seedBuyers)
    
    // Add initial history entries
    for (const buyer of seedBuyers) {
      await db.insert(buyerHistory).values({
        id: nanoid(),
        buyerId: buyer.id,
        changedBy: buyer.ownerId,
        changedAt: buyer.updatedAt,
        diff: JSON.stringify({ created: { old: null, new: "Buyer created" } })
      })
    }
    
    console.log("Database seeded successfully!")
  } catch (error) {
    console.error("Error seeding database:", error)
  }
}

// Run seed if this file is executed directly
if (require.main === module) {
  seedDatabase().then(() => process.exit(0))
}